### ISSUE TITLE
Working Example Anywhere?

### ISSUE THREAD

**Issue by Eater4** [zrrrzzt/osanywhereweather#67]
Is there a website with this api working anywhere? I just don't know where to start.

**Comment by zrrrzzt** [comment]
I'm not aware of any web implementations of this module.

What do you want to build?

You could use this module as a base for a rest/json API and connect your front-end to it. I can try to help you get a good start.

**Comment by Eater4** [comment]
Thanks for the reply. I am trying to build a simple website that shows the current wind speed, rain, and temperature. What I would like to accomplish is:

1. Parsing the json data that you get from the getLivedata example  in such a way that the values for the specific functions (rain, temp, wind etc) of the weather station from the data are extracted
2. With the extracted data, I plan to take those values and put them on a dashboard (possibly with something like [this](http://justgage.com/)
I believe that I can get the values from a generated json file and make the dashboard work with them. I cannot, however, get the actual json file. Im new and nodejs and npm, and I keep getting a require error.

Some other things that I would like to do (low priority)
1. Have the server send out a email when a sensor battery is low (php?)
2. Allow others to subscribe for alerts though email when sensors reach a certain value.

Again, thanks for the help. I always wanted to do this with the weather station, but Oregon Scientific is like Apple with weather stations and osanywhereweather (LW301) wont work with any other programs out there :/

**Comment by zrrrzzt** [comment]
The first two parts should be a good start. If you would like to write your front-page i something other than Node the best approach would probably be to do just the api-server in Node and the rest in the technology of your choice. If you want to learn Node and have your code in a repo on GitHub I can take a look at it there.

It looks like it's the live data you are most interested in and that would mean you API-server only needs one endpoint (or none if you're not planning to expand it)

I'm in the middle of rewriting this module at the moment to make it support promises so there is a gap between the version on GitHub and npm. I can add a simple example to the repo.

**Comment by Eater4** [comment]
Alright. Thanks again for this module :)

**Comment by zrrrzzt** [comment]
You're welcome :-)

I just created a repo called [osanywhereweather-api-server](https://github.com/zrrrzzt/osanywhereweather-api-server)
Take a look for an example of an API server.
